---
title: "01-exercises"
author: "Christopher Brown"
date: "April 6, 2016"
output: html_document
---


## Exercise 1:

Write a function (f) that takes a vector of numbers, **x**, and returns a vector of numbers such that each element containing the product of every element of x except the element of x with the same index. 


### Example 

    > x <- c( 1, 5, 2, 8 ) 
    > f(x) 
    [1] 80 16 40 10
    # 5*2*8, 1*2*8, 1*5*8, 1*2*5  


### Solution 

```{r}
takeInSomeNumbers <- function(x) {
  out <- 0
  for(i in x) {
        num <- 1
        for(j in x){
          if(j != i){
            num <- j * num
            
          }
        }
      out <- paste(out, sep=" ",num) 
    }
    return(out)
}

```
    



### Solution

```{r}
fizzyBuzzy <- function(x){
  
    fresult <- "Your Answer is:"
    
   for(i in x) 
   {
     y <- 0
     result <- i
     if((i %% 3) == 0)
     {
       result <-"Fizz"  
       y <- y + 1
     }
     if((i %% 5) == 0)
     {
       result <- "Buzz" 
        y <- y + 1
     }
     if(y==2)
     {
       result <- "FizzBuzz"
     }
     fresult <- paste(fresult, sep=" ",result)
     
   }
  return(fresult)
   }

```


